# Generated by Django 3.1.6 on 2021-02-11 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('is_web_push', models.BooleanField(default=False, verbose_name='Web Push')),
                ('is_sms', models.BooleanField(default=False, verbose_name='SMS')),
                ('is_email', models.BooleanField(verbose_name='Email')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
        ),
        migrations.CreateModel(
            name='WebPush',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=50, verbose_name='Site Name')),
                ('site_url', models.CharField(max_length=50, verbose_name='Site URL')),
                ('icon', models.FileField(upload_to='icons', verbose_name='Icon')),
                ('message_permission', models.CharField(max_length=100, verbose_name='Message Permission')),
                ('text_button_permission', models.CharField(max_length=50, verbose_name='Text Button Permission')),
                ('text_button_denied', models.CharField(max_length=50, verbose_name='Text Button Denied')),
                ('title_welcome', models.CharField(max_length=50, verbose_name='Title Welcome')),
                ('message_welcome', models.CharField(max_length=100, verbose_name='Message Welcome')),
                ('is_enabled_link', models.BooleanField(default=False, verbose_name='Enabled Link')),
                ('link_destination', models.CharField(max_length=50, verbose_name='Link Destination')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application', verbose_name='application')),
            ],
        ),
        migrations.CreateModel(
            name='Templates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('file', models.FileField(upload_to='template_email', verbose_name='Arquivo')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application', verbose_name='application')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50, verbose_name='Provider')),
                ('login', models.CharField(max_length=50, verbose_name='login')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application', verbose_name='application')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_name', models.CharField(max_length=50, verbose_name='SMTP Name')),
                ('smtp_port', models.SmallIntegerField(verbose_name='SMTP Port')),
                ('login', models.CharField(max_length=50, verbose_name='Login')),
                ('password', models.CharField(max_length=50, verbose_name='Senha')),
                ('sender_name', models.CharField(max_length=50, verbose_name='Sender Name')),
                ('sender_email', models.CharField(max_length=50, verbose_name='Sender Email')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.application', verbose_name='application')),
            ],
        ),
    ]
