# Generated by Django 3.1.6 on 2021-02-14 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='is_email',
            field=models.BooleanField(default=False, verbose_name='Email'),
        ),
    ]
