# Generated by Django 3.1.6 on 2021-02-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210214_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sms',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_sms', to='core.application'),
        ),
        migrations.AlterField(
            model_name='webpush',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_application', to='core.application'),
        ),
    ]
