# Generated by Django 3.1.6 on 2021-02-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210215_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email', to='core.application'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms', to='core.application'),
        ),
        migrations.AlterField(
            model_name='templates',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.application'),
        ),
        migrations.AlterField(
            model_name='webpush',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush', to='core.application'),
        ),
    ]
