# Generated by Django 3.1.6 on 2021-02-15 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210215_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(auto_now_add=True)),
                ('reading_date', models.DateField()),
                ('confirmation', models.BooleanField(default=False)),
                ('origem', models.CharField(choices=[('API', 'API'), ('PLA', 'Plataforma')], max_length=3)),
                ('email', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.email')),
                ('sms', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.sms')),
                ('webpush', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.webpush')),
            ],
        ),
    ]
