# Generated by Django 3.1.6 on 2021-02-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notificacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templates',
            name='application',
        ),
        migrations.AlterField(
            model_name='templates',
            name='file',
            field=models.FileField(upload_to='template_email', verbose_name='Template'),
        ),
    ]
