# Generated by Django 3.1.6 on 2021-02-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210215_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notificacao',
            new_name='Notification',
        ),
        migrations.RemoveField(
            model_name='email',
            name='template',
        ),
    ]
