# Generated by Django 3.1.6 on 2021-02-16 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210216_0028'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='origem',
            new_name='source',
        ),
    ]
