# Generated by Django 3.1.6 on 2021-02-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210216_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('API', 'API'), ('PLA', 'Plataforma')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
