# Generated by Django 3.1.6 on 2021-02-16 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_notification_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.email'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='send_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sms'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='webpush',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.webpush'),
        ),
    ]
